export const mrBertQuotes = [
  'Keep going. You’re not done.',
  'Drink water. Your brain needs it.',
  'One step. Then another. Simple.',
  'Relax. Not everything is urgent.',
  'You can handle more than you think.',
  'Breathe. Try again.',
  'Progress > perfection.',
  'Don’t rush. Move smart.',
  "You're closer than you feel.",
  'Reset your pace.',
  'Keep your mind sharp.',
  'Stand up. Stretch. Continue.',
  'Today is still fixable.',
  'Stop overthinking and start doing.',
  'You’ve survived worse.',
  'Trust your momentum.',
  'Small wins count.',
  'Don’t fold now.',
  'Focus beats luck.',
  "You're not stuck — just paused.",
  'Take the next tiny action.',
  'Control what you can.',
  'Your effort matters.',
  'Don’t waste energy on noise.',
  'Stay calm. Move forward.',
  'Consistency is louder than motivation.',
  'You’re learning — that’s progress.',
  'Shift your mindset, not the blame.',
  'Don’t let doubt drive.',
  'Reset your attitude, not your goals.',
  'You already know what to do.',
  'One task. Start it.',
  'Your future self is watching.',
  'Start slow if you must — just start.',
  'You deserve focus, not chaos.',
  'Keep your standards high.',
  'Don’t compete. Improve.',
  'Your pace is valid.',
  'Discomfort means you’re growing.',
  'Stay steady. You’re building something.',
];
